del /s /f *.pch
del /s /f *.pdb
del /s /f *.idb
del /s /f *.obj
del /s /f *.ncb
del /s /f *.exp
del /s /f *.manifest
del /s /f *.dep
del /s /f *.log
del /s /f *.tlog
del /s /f *.dep
del /s /f *.lastbuildstate
del /s /f *.unsuccessfulbuild
del /s /f *.cache
del /s /f *.ipch
del /s /f *.ilk
del /s /f *.sdf
del /s /f *.cod
